### PR TITLE
feat(raiko): run general tests on all targets

### PR DESCRIPTION
**Pull request by Brechtpd**
Not the nicest way to do it but it gets the job done especially because we don't have a lot of tests yet. We should split up general tests and tests that should run on all provers somehow.

Also currently depends on external RPC data which is not great but once we can create test blocks we can switch to that.

### CODE REVIEW

**Review by smtmfft — APPROVED** [review]
I think it still needs dynamic block number to avoid misleading blob deprecation error.

One more thought is: maybe some fixed input tests is also needed to make a kind of set of regression cases, but it generally ask for a stable input structure. Put it in todo for now :)

**Comment by Brechtpd** [comment]
> I think it still needs dynamic block number to avoid misleading blob deprecation error.

Right, will add!

> One more thought is: maybe some fixed input tests is also needed to make a kind of set of regression cases, but it generally ask for a stable input structure. Put it in todo for now :)

Ideally I think we can just generate test blocks directly, though having some cached real blocks may also be useful and easy.

**Comment by smtmfft** [comment]
SGX hw test env setup is done: https://github.com/smtmfft/raiko/pull/2

Can be updated after this one get merged.

**Comment by Brechtpd** [comment]
> SGX hw test env setup is done: [smtmfft#2](https://github.com/smtmfft/raiko/pull/2)
> 
> Can be updated after this one get merged.

Have to be a bit careful now with changed behavior: I made it so MOCK=1 enables SGX_DIRECT, and I currently set MOCK=1 in CI here:

image

So for running on actual SGX, make sure MOCK != 1.

**Comment by smtmfft** [comment]
> > SGX hw test env setup is done: [smtmfft#2](https://github.com/smtmfft/raiko/pull/2)
> > Can be updated after this one get merged.
> 
> Have to be a bit careful now with changed behavior: I made it so MOCK=1 enables SGX_DIRECT, and I currently set MOCK=1 in CI here:
> 
> So for running on actual SGX, make sure MOCK != 1.

HW CI Updated: https://github.com/taikoxyz/raiko/pull/175

**Pull request merged**
