### PR TITLE
Use get_proof in account data fetching to reduce number of RPC calls

### PR DESCRIPTION
**Pull request by Brechtpd**
Reduces the number of RPC calls for accounts from 3 to 2 (or even 1 if code fetching can be skipped when we know the code hash is empty).

I left the old code in for now because I see it working faster, but who knows how it might behave in different scenario's.

### CODE REVIEW

**Review by smtmfft — APPROVED** [review]

**Comment by smtmfft** [comment]
We have discussed using batch json RPC as json RPC support that feature, like 
```
[
  {"jsonrpc": "2.0", "method": "subtract",
    "params": {"subtrahend": 23, "minuend": 42}, "id": 1},
  {"jsonrpc": "2.0", "method": "xyz"},
  {"jsonrpc": "2.0", "method": "dummy", "id": 2},
]
```
However, here for get account, get_proof does exactly the same thing I think.
could be a option if in future multi-get_proof becomes the bottle neck.

**Comment by Brechtpd** [comment]
If get_proof would contain the code as well I think it would be the best it could be, but unfortunately still a separate call necessary now for that when there is code.

A batched (or I guess even a parallelized one on the client side to open multiple requests) get_proof would indeed help a lot for fetching the actual merkle proofs.

**Comment by smtmfft** [comment]
> A batched (or I guess even a parallelized one on the client side to open multiple requests) get_proof would indeed help a lot for fetching the actual merkle proofs.

Batch maybe easier to impl as no async issue? we can do it now and also control it with a feature flag. I can not remember why we did not impl it before A7, maybe because unstable is unstable and no perf pressure (due to plenty of op blocks).

**Comment by Brechtpd** [comment]
Oh I thought this required custom node support but it is actually supported by the standard json rpc API! Okay yeah we should support this! Will do this tomorrow if nobody else works on it in the meantime.

**Comment by smtmfft** [comment]
> Oh I thought this required custom node support but it is actually supported by the standard json rpc API! Okay yeah we should support this! Will do this tomorrow if nobody else works on it in the meantime.

"@Noboby Else" is already working on that for a while, let's fire him as you can complete it in a pretty short time :)

**Pull request merged**
